---

- name: "Copy krb5.conf"
  ansible.builtin.template:
    src: templates/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    backup: yes
    mode: '0644'

- name: restart kerberos
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - krb5kdc
    - kadmin